

version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: mytestdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-dump/backup_name.dump:/docker-entrypoint-initdb.d/mytestdb_dump.sql
    expose:
      - 5432


  mytest_api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db


volumes:
  postgres_data:
